version: '3'

services:
  db:
    container_name: db
    build: ./db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ../.tmp/postgresql:/var/lib/postgresql/data
  app:
    container_name: app
    build: ../app
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      APP_DB_HOST: db
      APP_DB_PORT: 5432
      APP_DB_NAME: postgres
      APP_DB_USER: user
      APP_DB_PASSWORD: password
